In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
iris.target_names
len(iris.data)

150

In [24]:
import numpy as np
## webから引用
def shuffle_samples(*args):
    # *argsで可変長引数を受け取る。変数argsにリストで格納される

    # unzipで複数配列のリスト -> 要素毎にまとめたタプルのリスト　に変換
    zipped = list(zip(*args))
    np.random.shuffle(zipped)

    # unzipして複数配列のリストの形に戻す
    shuffled = list(zip(*zipped))
    
    result = []
    # np.arrayに変換する処理
    for ar in shuffled:
        result.append(np.asarray(ar))
    return result

In [28]:

## knnは今回のスクラッチ実装
import knn 
LearnDataNum=int(len(iris.data)*0.8)
datasets=[]
testData=[]
### iris.data --> vec, iris.target --> specのインデックス
dataX,dataY=shuffle_samples(iris.data,iris.target)
for vec,specIdx in zip(dataX[:LearnDataNum],dataY[:LearnDataNum]):
    spec=iris.target_names[specIdx]
    data=knn.Data(vec,spec)
    datasets.append(data)
for vec,specIdx in zip(dataX[LearnDataNum:],dataY[LearnDataNum:]):
    spec=iris.target_names[specIdx]
    data=knn.Data(vec,spec)
    testData.append(data)

In [50]:
def predicts(testData):
    ans=[]
    for d in testData:
        c=knn.getNearVecSpec(d.vec,datasets,k=3)
        # print(c)
        cls=max(c,key=c.get)
        ans.append(cls)
    return ans

In [51]:
from sklearn.metrics import confusion_matrix
predict = predicts(testData)
y_test=[s.spec for s in testData]
print(confusion_matrix(y_test,predict,labels=iris.target_names))

[[11  0  0]
 [ 0  9  2]
 [ 0  0  8]]


In [54]:
## sklearn による K近傍法の実装を試す．
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=3)
train_x=[d.vec for d in datasets]
train_y=[d.spec for d in datasets]
test_x=[d.vec for d in testData]
test_y=[d.spec for d in testData]

clf.fit(train_x,train_y)
pre=clf.predict(test_x)
print(confusion_matrix(test_y,pre))

[[11  0  0]
 [ 0  9  2]
 [ 0  0  8]]
